version: '3.5'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty_123
      MYSQL_DATABASE: sys
    ports:
      - "3307:3306"
    volumes:
      - ./sys:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PROMETHEUS_SERVER_URL=http://10.0.2.9:9090
    volumes:
      - ./grafana_data:/var/lib/grafana
    user: "root"
    links:
      - prometheus:prometheus
    networks:
      - mynetwork

networks:
  mynetwork:
